   name: Auto Upload

   on:
     push:
       branches: [ main ]
     schedule:
       - cron: '0 0 * * *'  # 매일 자정에 실행

   jobs:
     upload:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run script
         run: python app.py
       - name: Commit files
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
           git diff-index --quiet HEAD || git commit -m "Auto update"
       - name: Push changes
         run: |
           git push origin main
